### ISSUE TITLE
background sync requests counts do not update

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa-demo#14]
![image](https://github.com/Spomky-Labs/phpwa-demo/assets/619585/0166a65b-ef42-45e9-a8d8-33aaea6745e7)

These numbers aren't updating when requests to add or delete are queued in background.

**Comment by Spomky** [comment]
Works fine here
![2024-03-11_20h25_03](https://github.com/Spomky-Labs/phpwa-demo/assets/1091072/759e3a47-4d19-43a1-bffa-1289af74079b)

Note that [you cannot use the offline option](https://developer.chrome.com/docs/workbox/modules/workbox-background-sync#testing_workbox_background_sync) in the dev tool. You must stop your server to test it.

**Comment by tacman** [comment]
Ah, I was testing it wrong.  Thx.
